apiVersion: v2
name: freqtrade
description: Fleet-oriented Helm chart for running Freqtrade dashboards and trading bots on Kubernetes
type: application
version: 0.3.2
appVersion: "stable"
home: https://www.freqtrade.io/
sources:
  - https://github.com/freqtrade/freqtrade
keywords:
  - freqtrade
  - crypto
  - trading
  - bot
  - kubernetes
  - helm
