mode:
  type: downloadData
  extraArgs:
    - --days
    - "14"
    - --pairs
    - BTC/USDT
    - BCH/USDT
    - ETH/USDT
    - LINK/USDT
    - LTC/USDT
    - SOL/USDT
    - BNB/USDT
    - XRP/USDT
    - ADA/USDT
    - DOT/USDT
    - ETC/USDT
    - ALGO/USDT
    - LUNA/USDT
    - --timeframes
    - 15m

config:
  public:
    dry_run: true
    exchange:
      name: binance
      key: ""
      secret: ""
      ccxt_config: {}
      ccxt_async_config: {}

api:
  enabled: false

service:
  enabled: false

persistence:
  enabled: true
  existingClaim: freqtrade-webserver-user-data

nodeSelector:
  kubernetes.io/hostname: poseidon

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
