{{- include "freqtrade.validate" . }}
{{- if and (ne (include "freqtrade.mode.isStateful" .) "true") .Values.mode.schedule.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "freqtrade.fullname" . }}
  labels:
    {{- include "freqtrade.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.mode.schedule.cron | quote }}
  suspend: {{ .Values.mode.schedule.suspend }}
  concurrencyPolicy: {{ .Values.mode.schedule.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.mode.schedule.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.mode.schedule.failedJobsHistoryLimit }}
  {{- with .Values.mode.schedule.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ . }}
  {{- end }}
  {{- with .Values.mode.schedule.timeZone }}
  timeZone: {{ . | quote }}
  {{- end }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.mode.job.backoffLimit }}
      ttlSecondsAfterFinished: {{ .Values.mode.job.ttlSecondsAfterFinished }}
      {{- with .Values.mode.job.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ . }}
      {{- end }}
      template:
        metadata:
          labels:
            {{- include "freqtrade.selectorLabels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          annotations:
            {{- include "freqtrade.podAnnotations" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "freqtrade.serviceAccountName" . }}
          automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
          terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
          {{- with .Values.image.pullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- $strategyInit := include "freqtrade.strategyInitContainer" . | trim }}
          {{- if or $strategyInit .Values.initContainers }}
          initContainers:
            {{- if $strategyInit }}
            {{- $strategyInit | nindent 12 }}
            {{- end }}
            {{- with .Values.initContainers }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          containers:
            - name: freqtrade
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              securityContext:
                {{- toYaml .Values.containerSecurityContext | nindent 16 }}
              {{- with .Values.command }}
              command:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- if .Values.args }}
              args:
                {{- toYaml .Values.args | nindent 16 }}
              {{- else }}
              args:
                {{- include "freqtrade.containerArgs" . | nindent 16 }}
              {{- end }}
              {{- with .Values.envFrom }}
              envFrom:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.env }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              {{- with .Values.lifecycle }}
              lifecycle:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
                {{- include "freqtrade.volumeMounts" . | nindent 16 }}
            {{- with .Values.extraContainers }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumes:
            {{- include "freqtrade.volumes" . | nindent 12 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.topologySpreadConstraints }}
          topologySpreadConstraints:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.priorityClassName }}
          priorityClassName: {{ . }}
          {{- end }}
{{- end }}

