{{- include "freqtrade.validate" . }}
{{- if .Values.config.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-external-secret" (include "freqtrade.fullname" .) }}
  labels:
    {{- include "freqtrade.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.config.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.config.externalSecret.secretStoreRef.kind }}
    name: {{ required "config.externalSecret.secretStoreRef.name is required when externalSecret is enabled" .Values.config.externalSecret.secretStoreRef.name }}
  target:
    name: {{ include "freqtrade.privateConfigSecretName" . }}
    creationPolicy: {{ .Values.config.externalSecret.target.creationPolicy }}
    deletionPolicy: {{ .Values.config.externalSecret.target.deletionPolicy }}
  {{- with .Values.config.externalSecret.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.config.externalSecret.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

