{{- include "freqtrade.validate" . }}
{{- $ingress := .Values.ui.ingress }}
{{- if and $ingress.enabled .Values.api.enabled .Values.service.enabled (eq (include "freqtrade.mode.isStateful" .) "true") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "freqtrade.fullname" . }}
  labels:
    {{- include "freqtrade.labels" . | nindent 4 }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    {{- range $ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "freqtrade.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
  {{- with $ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
