{{- include "freqtrade.validate" . }}
{{- if and (not .Values.config.existingSecret) (not .Values.config.externalSecret.enabled) (not (empty .Values.config.sensitive)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freqtrade.privateConfigSecretName" . }}
  labels:
    {{- include "freqtrade.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.config.existingSecretKey }}: |
{{ toPrettyJson .Values.config.sensitive | nindent 4 }}
{{- end }}

